default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 7c08e8712k
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_webpack_development

test:
  <<: *default
  database: rails_webpack_test


production:
  <<: *default
  database: rails_webpack_production