Greeting.create(message: 'Hello, Walid!')
Greeting.create(message: 'Hello, Microverse!')
Greeting.create(message: 'Hello, React!')
Greeting.create(message: 'Hello, Rails!')
Greeting.create(message: 'Hello, Ruby!')
